--EJEMPLO DE AGRUPACIÓN NO SIGNIFICATIVA
SELECT    C.NOMEQ, DIRECTOR  
FROM      CICLISTA C, EQUIPO E
WHERE     C.NOMEQ=E.NOMEQ
GROUP BY  C.NOMEQ, DIRECTOR
HAVING    COUNT(*)>3 AND
          AVG(EDAD)<=30;