SELECT    	NOMBRE, COUNT(*)  
FROM      	ETAPA E, CICLISTA C     
WHERE		E.DORSAL=C.DORSAL
GROUP BY  	E.DORSAL, NOMBRE;

--OBSERVA BIEN LA AGRUPACIÓN! DORSAL NO PUEDE FALTAR AUNQUE NO SE PIDA EN EL SELECT!