SELECT C.NOMEQ, COUNT(*)
FROM  CICLISTA C, ETAPA E
WHERE C.DORSAL=E.DORSAL
GROUP BY C.NOMEQ
HAVING COUNT(*)=  (SELECT MAX(COUNT(*))
                  FROM    CICLISTA C1, ETAPA E1
                  WHERE   C1.DORSAL=E1.DORSAL
                  GROUP BY C1.NOMEQ);