--AGRUPACIÓN NO SIGNIFICATIVA
--OBSERVA QUE: 
	--NO SE NECESITAN TODAS LAS TABLAS EN LA SUBCONSULTA
	--NOMEQ ES NECESARIO EN LA AGRUPACIÓN AUNQUE NO SE MUESTRE
SELECT    DIRECTOR, COUNT(*)  
FROM      EQUIPO, CICLISTA, LLEVAR
WHERE     EQUIPO.NOMEQ=CICLISTA.NOMEQ AND
          CICLISTA.DORSAL=LLEVAR.DORSAL     
GROUP BY  EQUIPO.NOMEQ, DIRECTOR
HAVING    COUNT(*)= (SELECT   MAX(COUNT(*))
                    FROM      CICLISTA, LLEVAR
                    WHERE     CICLISTA.DORSAL=LLEVAR.DORSAL     
                    GROUP BY  NOMEQ);