SELECT  DISTINCT CODIGO
FROM    LLEVAR
WHERE   DORSAL NOT IN  (SELECT 	DISTINCT DORSAL
			FROM    ETAPA);

--VERSIÓN EXISTS
SELECT  DISTINCT CODIGO
FROM    LLEVAR
WHERE   NOT EXISTS  (SELECT *
                    FROM    ETAPA
                    WHERE   LLEVAR.DORSAL=ETAPA.DORSAL);