SELECT  DISTINCT LLEVAR.CODIGO, COLOR
FROM    LLEVAR, MAILLOT
WHERE   LLEVAR.CODIGO=MAILLOT.CODIGO AND
        DORSAL NOT IN  (SELECT 	DISTINCT DORSAL
			FROM    ETAPA);


--VERSIÓN EXISTS
SELECT  DISTINCT LLEVAR.CODIGO, COLOR
FROM    LLEVAR, MAILLOT
WHERE   LLEVAR.CODIGO=MAILLOT.CODIGO AND
        NOT EXISTS  (SELECT *
                    FROM    ETAPA
                    WHERE   LLEVAR.DORSAL=ETAPA.DORSAL);