DROP TABLE EQUIPO CASCADE CONSTRAINTS;
DROP TABLE CICLISTA CASCADE CONSTRAINTS;
DROP TABLE ETAPA CASCADE CONSTRAINTS;
DROP TABLE PUERTO CASCADE CONSTRAINTS;
DROP TABLE MAILLOT CASCADE CONSTRAINTS;
DROP TABLE LLEVAR CASCADE CONSTRAINTS;