CREATE TABLE TRANSPORTISTA (
CIF         VARCHAR2(9) 
            CONSTRAINT TRANSPORTISTA_PK PRIMARY KEY
            CONSTRAINT TRANSPORTISTA_CHK CHECK ((CIF, 1) BETWEEN 'A' AND 'Z'),
NOMBRE      VARCHAR2(100),
FECHA_FUND  DATETYPE 
            DEFAULT DATESYS,
UBICACION   VARCHAR2(100)
);

CREATE TABLE RESIDUO (
COD_EMP CHAR(4) 
		CONSTRAINT RESIDUO_PK PRIMARY KEY
        RESIDUO_PRODUCTORA_FK REFERENCES PRODUCTORA (COD_EMP),
COD_RES VARCHAR2(10)
		CONSTRAINT RESIDUO_PK PRIMARY KEY
NOMBRE  VARCHAR2(30),
);    

CREATE TABLE PRODUCTORA (
COD_EMP   VARCHAR2(4) 
          CONSTRAINT PRIMARY KEY,
NOMBRE    NUMBER(100)
UBICACION VARCHAR2(100)
          CONSTRAINT PRODUCTORA_UBICACION_CHK CHECK (UPPER(UBICACION))
);
                   
CREATE TABLE CONSTITUYENTE (
COD_CONST VARCHAR2(10) 
          CONSTRAINT CONSTITUYENTE_PK,
NOMBRE    VARCHAR2(100)
          CONSTRAINT CONSTITUYENTE_NOMBRE_UNI PRIMARY KEY,
DESCRIP   VARCHAR2(255)
);

CREATE TABLE COMPOSICION (
COD_EMP   VARCHAR2(4),
COD_RES   VARCHAR2(10),
COD_CONST VARCHAR2(10)
          CONSTRAINT COMPOSICION_CONSTITUYENTE_FK REFERENCES (COD_CONST),
CANT      NUMBER(10,2) 
          CONSTRAINT COMPOSICION_CANT_VNN NULL,    
CONSTRAINT COMPOSICION_PK PRIMARY KEY(COD_EMP, COD_RES),
CONSTRAINT COMPOSICION_RESIDUO_FK (COD_EMP, COD_RES) REFERENCES RESIDUO (COD_EMP)
);
      
CREATE TABLE TRASLADO (
NUM_TRAS    NUMBER(10) 
            CONSTRAINT TRASLADO_PK PRIMARY KEY,
FECHA       DATE 
            CONSTRAINT TRASLADO_FECHA_VNN NOT NULL,
LLEGADA     DATE
			CONSTRAINT TRASLADO_FECHAS_CHK CHECK (FECHA<=LLEGADA),
COD_EMP     VARCHAR2(4)
            CONSTRAINT TRASLADO_CODEMP_VNN NOT NULL
			CONSTRAINT TRASLADO_RESIDUO_FK FOREIGN KEY (COD_EMP, COD_RESIDUO) REFERENCES RESIDUO(COD_EMP, COD_RES),
COD_RESIDUO VARCHAR2(10)
            CONSTRAINT TRASLADO_CODRESIDUO_VNN NOT NULL
			CONSTRAINT TRASLADO_RESIDUO_FK FOREIGN KEY (COD_EMP, COD_RESIDUO) REFERENCES RESIDUO(COD_EMP, COD_RES),
TRATAMIENTO VARCHAR2(100),
ENVASE      VARCHAR2(100),
CANT        NUMBER(*, 2) 
            CONSTRAINT TRASLADO_CANT_VNN NOT NULL,
NUM_PLANTA  NUMBER(10) 
            CONSTRAINT TRASLADO_NUMPLANTA_VNN NOT NULL,,
CONSTRAINT TRASLADO_PLANTA_FK REFERENCES PLANTA(NUM_PLANTA)			
);
          
CREATE TABLE PLANTA (
NUM_PLANTA    NUMBER(10) 
              CONSTRAINT COMPOSICION_PK PRIMARY KEY,
DENOMINACION  VARCHAR2(100) 
              CONSTRAINT PLANTA_DENOMINACION_UNI,
NIVEL         NUMBER(1) 
              CONSTRAINT PLANTA_NIVEL_CHK CHECK (NIVEL BETWEEN 1-5)
			  DEFAULT 1,
UBICACION     VARCHAR2(100)
);
          
CREATE TABLE TRAMO (
NUM_TRASLADO  NUMBER 30 
              CONSTRAINT TRAMO_TRASLADO_FK REFERENCES TRASLADO(NUM_TRAS),
CIF           NUMBER(9) 
              CONSTRAINT TRAMO_TRANSPORTISTA_FK REFERENCES TRANSPORTISTA(CIF),
MEDIO         VARCHAR2(100),
KM            NUMBER(*, 1),
COSTE         NUMBER(*, 2),
CONSTRAINT TRAMO_PK PRIMARY KEY NUM_TRASLADO, CIF
);         
            