SELECT	NUMCOL,NOMBRE,ESPECIALIDAD,ALTA, NOMBRE || ': ' || ESPECIALIDAD || '. Colegiad@ actualmente en el colegio: ' || SUBSTR(NUMCOL, -9,2) || ' con Nº correlativo: ' || SUBSTR(NUMCOL, -5,5) AS "DATOS HACIENDA"
FROM	MEDICO
WHERE	(NUMCOL LIKE '__03%' OR NUMCOL LIKE '__46%' OR NUMCOL LIKE '__12%') AND ESPECIALIDAD = 'DIGESTIVO'
	
	