--1
ALTER SESSION SET NLS_DATE_FORMAT = 'd month yyyy';
--2
ALTER SESSION SET NLS_DATE_FORMAT = 'day dd month yyyy';
--3
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy';
--4
ALTER SESSION SET NLS_DATE_FORMAT = 'yy/mm/dd';
--5
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi';


SELECT SYSDATE
FROM DUAL;