SELECT CONCEPTO, NVL(PRECIOUD,0) PRECIO, ROUND(NVL(PRECIOUD,0)) "Precio Redondeado", CEIL(NVL(PRECIOUD,0)) "Entero Superior", FLOOR(NVL(PRECIOUD,0)) "Entero Inferior"
FROM GASTOS
WHERE LOWER (CONCEPTO) LIKE '%t%';