SELECT 	CODCLI
FROM 	FACTURA
WHERE 	TO_CHAR(FECHA, 'YYYY') IN ('2002') AND
	TO_CHAR(FECHA, 'MM') IN ('9','10','11' ,'12');
	
SELECT 	CODCLI
FROM 	FACTURA
WHERE 	TO_CHAR(FECHA, 'YYYY') IN ('2002') AND
	TO_CHAR(FECHA, 'MM') IN ('5','6','7' ,'8');