SELECT 	CODFAC, FECHA, CODCLI
FROM 	FACTURA
WHERE 	MOD(CODCLI,10) = 0 AND
	TO_CHAR(FECHA, 'YYYY') = '2002';


SELECT 	CODFAC, FECHA, TO_CHAR(CODCLI)
FROM 	FACTURA
WHERE 	SUBSTR(TO_CHAR(CODCLI), -1)='0' AND
	TO_NUMBER(TO_CHAR(FECHA, 'YYYY')) = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))-1;