SELECT CODFAC, FECHA
FROM FACTURA
WHERE TO_CHAR(FECHA, 'YYYY') IN ('2000', '2001', '2002')
AND TO_CHAR(FECHA, 'MM') = '05';

SELECT CODFAC, FECHA
FROM FACTURA
WHERE TO_CHAR(FECHA, 'YYYY') BETWEEN TO_CHAR(SYSDATE, 'YYYY') - 2 AND TO_CHAR(SYSDATE, 'YYYY')
AND TO_CHAR(FECHA, 'MM') = '05';
