CREATE TABLE USUARIO(
NOMUSU		VARCHAR2(30) 
		CONSTRAINT USUARIO_PK PRIMARY KEY,
PROCEDENCIA	VARCHAR2(50),
EMAIL		VARCHAR2(50) 
		CONSTRAINT USUARIO_EMAIL_VNN NOT NULL
		CONSTRAINT USUARIO_EMAIL_UNI UNIQUE,
ALTA		DATE
		DEFAULT SYSDATE,
PWD     	VARCHAR2(20) 
		CONSTRAINT USUARIO_PWD_VNN NOT NULL
		CONSTRAINT USUARIO_PWD_CHK CHECK (LENGTH(PWD) >= 8)
);

CREATE TABLE INGREDIENTE(
CODING  	VARCHAR2(10) 
		CONSTRAINT INGREDIENTE_PK PRIMARY KEY, 
NOMBRE	    	VARCHAR2(20)
		CONSTRAINT INGREDIENTE_NOMBRE_VNN NOT NULL,
DESCRIP		VARCHAR2(1000),
CALORIAS	NUMBER(5) 
		DEFAULT 0
);

CREATE TABLE RECETA(
CODREC  	VARCHAR2(10) 
    		CONSTRAINT RECETA_PK PRIMARY KEY, 
TITULO		VARCHAR2(100)
		CONSTRAINT RECETA_TITULO_VNN NOT NULL,
USUARIO		VARCHAR2(30)
		CONSTRAINT RECETA_USUARIO_FK REFERENCES USUARIO (NOMUSU) 
			ON DELETE SET NULL,
PROCEDENCIA	VARCHAR2(50),
DIFICULTAD	VARCHAR2(7)
		CONSTRAINT RECETA_DIFICULTAD_CHK CHECK (UPPER(DIFICULTAD) IN ('FÁCIL', 'MEDIA', 'DIFÍCIL'))
);

CREATE TABLE DESGLOSE(
CODREC 	VARCHAR2(10)
        CONSTRAINT DESGLOSE_RECETA_FK REFERENCES RECETA (CODREC) 
		ON DELETE CASCADE,
CODING	VARCHAR2(10)
        CONSTRAINT DESGLOSE_INGREDIENTE_FK REFERENCES INGREDIENTE (CODING),
CANT	NUMBER(5,2)
        CONSTRAINT DESGLOSE_CANT_VNN NOT NULL
        CONSTRAINT DESGLOSE_CANT_CHK CHECK (CANT > 0),
MEDIDA  VARCHAR2(2)
        DEFAULT 'UD'
        CONSTRAINT DESGLOSE_MEDIDA_CHK CHECK (UPPER(MEDIDA) IN ('UD', 'GR', 'MG', 'KG', 'L', 'ML')),
CONSTRAINT CANTIDAD_PK PRIMARY KEY (CODING, CODREC)
);

CREATE TABLE PASOS(
CODREC	VARCHAR2(10)
        CONSTRAINT PASOS_RECETA_FK REFERENCES RECETA (CODREC) 
		ON DELETE CASCADE,
NUMERO	NUMBER(2),
        CONSTRAINT PASOS_NUMERO_CHK CHECK (NUMERO<=15), 
DESCRIP	VARCHAR2(1000),
CONSTRAINT PASOS_PK PRIMARY KEY (CODREC, NUMERO)
);

CREATE TABLE VALORACION(
CODREC 	    	VARCHAR2(10) 
		CONSTRAINT VALORACION_RECETA_FK REFERENCES RECETA (CODREC) 
			ON DELETE CASCADE,
USUARIO     	VARCHAR2(30)
		CONSTRAINT VALORACION_USUARIO_FK REFERENCES USUARIO (NOMUSU) 
			ON DELETE CASCADE,
OPINION	    	VARCHAR2(1000),
PUNTUACION	NUMBER(3,1)
		CONSTRAINT VALORACION_PUNTUACION_VNN NOT NULL
		CONSTRAINT VALORACION_PUNTUACION_CHK CHECK (PUNTUACION BETWEEN 0 AND 10),
FECHA		DATE 
		DEFAULT SYSDATE,
CONSTRAINT VALORACION_PK PRIMARY KEY (CODREC, USUARIO)
);
