SELECT P.NOMBRE, COUNT(C.CODCLI)
FROM PROVINCIA P, CLIENTE C, CPOSTAL CP, LOCALIDAD L
WHERE C.CODPOSTAL = CP.CODPOSTAL AND
	CP.CODLOC = L.CODLOC AND
	P.CODPROV = L.CODPROV
GROUP BY P.CODPROV,P.NOMBRE
HAVING COUNT(CODCLI) > 5;