SELECT F.CODCLI, C.NOMBRE, COUNT(FL.CODART), FL.CODART	
FROM FACTURA_LINEA FL, FACTURA F, CLIENTE C
WHERE FL.CODFAC = F.CODFAC AND
	C.CODCLI = F.CODCLI
GROUP BY F.CODCLI, C.NOMBRE, FL.CODART
HAVING SUM(FL.CANT) >= 20
