SELECT COUNT(C.CODCLI),L.NOMBRE, P.NOMBRE
FROM CLIENTE C, LOCALIDAD L, PROVINCIA P, CPOSTAL CP
WHERE C.CODPOSTAL = CP.CODPOSTAL AND
	CP.CODLOC = L.CODLOC AND
	L.CODPROV = P.CODPROV AND
	P.CODPROV IN (12,46,03)
GROUP BY L.NOMBRE, P.NOMBRE