SELECT      C.NOMBRE, C.DIRECCION, COUNT(F.CODFAC)
FROM        CLIENTE C, CPOSTAL CP, LOCALIDAD L, PROVINCIA P, FACTURA F
WHERE       C.CODCLI = F.CODCLI AND
            C.CODPOSTAL = CP.CODPOSTAL AND
            CP.CODLOC = L.CODLOC AND
            L.CODPROV = P.CODPROV AND
            UPPER(P.NOMBRE) = 'CASTELLON' AND
            TO_CHAR(FECHA, 'YYYY') = '2002'
GROUP BY    C.CODCLI,C.NOMBRE, C.DIRECCION;