SELECT C.NOMBRE,C.CODPOSTAL, SUM(FL.CANT * FL.PRECIO) "FACTURADO"
FROM CLIENTE C, FACTURA F, FACTURA_LINEA FL
WHERE C.CODCLI = F.CODCLI AND
	F.CODFAC = FL.CODFAC
GROUP BY C.CODCLI,C.NOMBRE,C.CODPOSTAL
HAVING SUM(FL.CANT * FL.PRECIO) >= (6000);