SELECT F.CODVEN, V.NOMBRE, COUNT(DISTINCT FL.CODART)
FROM VENDEDOR V, FACTURA F, FACTURA_LINEA FL
WHERE F.CODVEN = V.CODVEN AND
	F.CODFAC = FL.CODFAC AND
	UPPER(FL.CODART) LIKE 'B%'
GROUP BY F.CODVEN, V.NOMBRE
HAVING COUNT(DISTINCT(FL.CODART)) >= 8;
