SELECT C.CODCLI, C.NOMBRE
FROM CLIENTE C
WHERE C.CODCLI IN (
    SELECT F.CODCLI
    FROM FACTURA F
    WHERE TO_CHAR(F.FECHA, 'MM/YYYY') = '12/2002'
    AND F.CODFAC IN (
        SELECT FL.CODFAC
        FROM FACTURA_LINEA FL
        GROUP BY FL.CODFAC
        HAVING SUM(FL.CANT * FL.PRECIO) > 60));

--FROM COMPUESTO
SELECT C.CODCLI, C.NOMBRE
FROM CLIENTE C, FACTURA F, FACTURA_LINEA FL
WHERE F.CODCLI = C.CODCLI AND
	F.CODFAC = FL.CODFAC AND
	TO_CHAR(F.FECHA, 'MM/YYYY') = '12/2002'
GROUP BY C.CODCLI, C.NOMBRE
HAVING SUM(FL.CANT * FL.PRECIO) > 60;