/*2*/
CREATE TABLE ESTUDIANTE (
NIA NUMBER (8), 
NOMBRE VARCHAR2(50),
CONSTRAINT ALUMNO_PK PRIMARY KEY (NIA),
CONSTRAINT NOMBRE_VNN CHECK (NOMBRE IS NOT NULL)
);
/*3*/
INSERT INTO ESTUDIANTE (NIA,NOMBRE)
VALUES (12345678,'MANOLITO COMPUTER');

/*4*/
ALTER TABLE ESTUDIANTE 
ADD (FNAC DATE);

/*5*/
INSERT INTO ESTUDIANTE (NIA,NOMBRE,FNAC)
VALUES (11111111,'CARMEN MOUSE','30/09/08');

/*6*/
INSERT INTO ESTUDIANTE (NIA)
VALUES (22222222);

/*7*/
UPDATE ESTUDIANTE
SET FNAC = '01/08/2001'
WHERE NIA = 12345678;


/*8*/
DELETE FROM ESTUDIANTE
WHERE FNAC < '01/01/2005';

/*9*/
ALTER TABLE ESTUDIANTE
DROP CONSTRAINT NOMBRE_VNN;

/*10*/
INSERT INTO ESTUDIANTE (NIA)
VALUES (22222222);


/*11*/
ALTER TABLE ESTUDIANTE
ADD CONSTRAINT NOMBRE_VNN CHECK (NOMBRE IS NOT NULL);


/*12*/
ALTER TABLE ESTUDAINTE
ADD (CONSTRAINT NOMBRE_ESTUDIANTE_UNIQUE UNIQUE (NOMBRE));

/*13*/
CREATE TABLE ASIGNATURA (
             COD        VARCHAR2(7)
                        CONSTRAINT ASIGNATURA_PK PRIMARY KEY,
             NOMBRE     VARCHAR2(50),
             CREDITOS   NUMBER(5,2)
);

/*14*/
INSERT INTO ASIGNATURA VALUES ('BD', 'BASE DE DATOS', 100);

/*15*/
ALTER TABLE ASIGNATURA
ADD 	HSEM NUMBER(2,1)
	CONSTRAINT ASIGNATURA_HSEM_VNN NOT NULL;
	
/*16*/
CREATE TABLE MATRICULA (
NIA 	NUMBER(8)
	CONSTRAINT MATRICULA_ESTUDIANTE_FK REFERENCES ESTUDIANTE (NIA),
COD	VARCHAR2(7)
	CONSTRAINT MATRICULA_ASIGNATURA_FK REFERENCES ASIGNATURA (COD),
NOTA	NUMBER(4,2),
CONSTRAINT MATRICULA_PK PRIMARY KEY (NIA, COD)
);

/*17*/
INSERT INTO MATRICULA (NIA,COD) VALUES (11111111, 'BD');

/*18*/
INSERT INTO MATRICULA (NIA, COD, NOTA)
VALUES (22222222, 'BD', 10);

/*19*/
UPDATE MATRICULA
SET NOTA = NOTA/2
WHERE TO_CHAR(NIA) NOT LIKE '1%'; 

SELECT *
FROM MATRICULA;

/*20*/
ALTER TABLE MATRICULA
    DROP CONSTRAINT MATRICULA_ESTUDIANTE_FK;
ALTER TABLE MATRICULA
    DROP CONSTRAINT MATRICULA_ASIGNATURA_FK;


ALTER TABLE MATRICULA
    MODIFY(
    NIA NUMBER(8)
    CONSTRAINT MATRICULA_ESTUDIANTE_FK REFERENCES ESTUDIANTE (NIA) ON DELETE CASCADE,
    COD VARCHAR2(7)
    CONSTRAINT MATRICULA_ASIGNATURA_FK REFERENCES ASIGNATURA (COD) ON DELETE CASCADE
    );

ALTER TABLE MATRICULA
    ADD(
        CONSTRAINT MATRICULA_ESTUDIANTE_FK FOREIGN KEY (NIA) REFERENCES ESTUDIANTE (NIA) ON DELETE CASCADE,
        CONSTRAINT MATRICULA_ASIGNATURA_FK FOREIGN KEY (COD) REFERENCES ASIGNATURA (COD) ON DELETE CASCADE
        );

/*21*/
DELETE ESTUDIANTE
WHERE TO_CHAR(NIA) LIKE '%2%';

/*22*/
DELETE ESTUDIANTE;

/*23*/
DELETE MATRICULA;

/*24*/
DELETE ASIGNATURA;


COMMIT;

SELECT *
FROM ESTUDIANTE;