SELECT  DISTINCT  L1.NOMBRE
FROM    LOCALIDAD L1, LOCALIDAD L2, PROVINCIA P1, PROVINCIA P2
WHERE   L1.CODPROV = P1.CODPROV AND
        L1.NOMBRE = L2.NOMBRE AND
        UPPER(P1.NOMBRE) = 'CASTELLON' AND
        P2.CODPROV = L2.CODPROV AND
        UPPER(P2.NOMBRE) != 'CASTELLON';
        