SELECT  F.CODFAC, FECHA, C.NOMBRE, V.NOMBRE
FROM    FACTURA F, CLIENTE C, VENDEDOR V
WHERE   C.CODCLI = F.CODCLI AND
        V.CODVEN = F.CODVEN AND
	(SELECT     COUNT(*)
        FROM        FACTURA_LINEA FL
        WHERE       FL.CODFAC = F.CODFAC) BETWEEN 4 AND 6;
