SELECT  V.NOMBRE, L.NOMBRE, VE.NOMBRE
FROM    VENDEDOR V, VENDEDOR VE, CPOSTAL CP, LOCALIDAD L, PROVINCIA P
WHERE   V.CODJEFE = VE.CODVEN AND
	V.CODPOSTAL = CP.CODPOSTAL AND 
	CP.CODLOC = L.CODLOC AND
	L.CODPROV = P.CODPROV AND 
	UPPER(P.NOMBRE) LIKE 'CASTELLON';