SELECT CODART, DESCRIP, PRECIO
FROM ARTICULO
WHERE PRECIO > (SELECT PRECIO
		FROM ARTICULO
		WHERE CODART='SATF4');
		
SELECT A1.CODART, A1.DESCRIP, A1.PRECIO, A2.PRECIO
FROM ARTICULO A1, ARTICULO A2
WHERE A2.CODART = 'SATF4' AND 
	A1.PRECIO > A2.PRECIO;