SELECT  V.NOMBRE, VE.NOMBRE
FROM    VENDEDOR V, VENDEDOR VE, CPOSTAL CP, LOCALIDAD L
WHERE   V.CODJEFE = VE.CODVEN AND 
	V.CODPOSTAL = CP.CODPOSTAL AND
	CP.CODLOC = L.CODLOC AND 
	UPPER(L.NOMBRE) LIKE 'MONTANEJOS';