SELECT C.NOMBRE, C.DIRECCION, COUNT(CODFAC)
FROM CLIENTE C LEFT JOIN CPOSTAL CP ON CP.CODPOSTAL = C.CODPOSTAL 
LEFT JOIN LOCALIDAD L ON L.CODLOC = CP.CODLOC
LEFT JOIN PROVINCIA P ON P.CODPROV = L.CODPROV
LEFT JOIN FACTURA F ON F.CODCLI = C.CODCLI
WHERE UPPER(P.NOMBRE) LIKE 'CASTELLON' AND
	TO_CHAR(F.FECHA,'YYYY') LIKE '2002'
GROUP BY C.NOMBRE, C.DIRECCION