SELECT A.CODART, A.DESCRIP, COUNT(CODFAC)
FROM ARTICULO A LEFT JOIN FACTURA_LINEA FL ON A.CODART = FL.CODART
WHERE A.CODART LIKE 'IM2%' AND
	UPPER(A.DESCRIP) LIKE '%INTERRUPTOR%'
GROUP BY A.CODART, A.DESCRIP