SELECT A.CODART, A.DESCRIP, SUM(NVL(FL.CANT,0))
FROM ARTICULO A LEFT JOIN FACTURA_LINEA FL ON A.CODART = FL.CODART
WHERE A.CODART LIKE 'IM2%' AND
	UPPER(A.DESCRIP) LIKE '%INTERRUPTOR%'
GROUP BY A.CODART, A.DESCRIP