DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE SALA CASCADE CONSTRAINTS;
DROP TABLE CITA CASCADE CONSTRAINTS; 
DROP TABLE VISITA CASCADE CONSTRAINTS;
DROP TABLE EXPERIENCIA CASCADE CONSTRAINTS;