CREATE TABLE MEDICO (
NUMCOL      NUMBER(9) 
            CONSTRAINT MEDICO_PK PRIMARY KEY, 
NOMBRE      VARCHAR2(50) 
            NOT NULL, 
ESPECIALIDAD CHAR(20), 
ALTA        DATE
);

CREATE TABLE PACIENTE (
CODPAC  VARCHAR2(50) 
        CONSTRAINT PACIENTE_PK PRIMARY KEY, 
NOMBRE  VARCHAR2(50) 
        NOT NULL, 
ALTA    DATE,
TIPO    VARCHAR2(10) 
        CHECK (TIPO IN ('HABITUAL', 'ESPORADICO', 'VIP')),
TFNO    VARCHAR2(10), 
EMAIL   VARCHAR(25)
);

CREATE TABLE SALA (
NUMSALA     NUMBER(3) 
            CONSTRAINT SALA_PK PRIMARY KEY, 
UBICACION   VARCHAR2(50) 
);

CREATE TABLE CITA (
FECHA   DATE,
HORA    VARCHAR(5), 
PACIENTE VARCHAR2(50) 
        CONSTRAINT CITA_PACIENTE_FK REFERENCES PACIENTE (CODPAC),
MEDICO  NUMBER(9) 
        NOT NULL
        CONSTRAINT CITA_MEDICO_FK REFERENCES MEDICO (NUMCOL),
OBSERVACIONES VARCHAR2(255),
CONSTRAINT CITA_PK PRIMARY KEY (FECHA, HORA, PACIENTE),
CONSTRAINT CITA_UNI UNIQUE (FECHA, HORA, MEDICO)
);

CREATE TABLE VISITA (
NUMVISITA   NUMBER 
            CONSTRAINT VISITA_PK PRIMARY KEY, 
FECHA       DATE 
            NOT NULL,
HORA        VARCHAR(5), 
PACIENTE    VARCHAR2(50),
SALA        NUMBER (3) 
            CONSTRAINT VISITA_SALA_FK REFERENCES SALA (NUMSALA),
DIAGNOSTICO VARCHAR2(255),
PRECIO      NUMBER(4,2),
CONSTRAINT VISITA_UNI UNIQUE (FECHA, HORA, PACIENTE),
CONSTRAINT VISITA_CITA_FK FOREIGN KEY (FECHA, HORA, PACIENTE) REFERENCES CITA (FECHA, HORA, PACIENTE)
);

CREATE TABLE EXPERIENCIA (
NUMVISITA   NUMBER 
            CONSTRAINT EXPERIENCIA_PK PRIMARY KEY 
            CONSTRAINT EXPERIENCIA_VISITA_FK REFERENCES VISITA (NUMVISITA),
EXPERIENCIA VARCHAR2(255), 
VALORACION  NUMBER(2) 
            CHECK (VALORACION BETWEEN 0 AND 10)
);