CREATE TABLE PROYECTO (
CODPROY 	VARCHAR2(5)
		CONSTRAINT PROYECTO_CODPROY_PK PRIMARY KEY,
INICIO 		DATE
		CONSTRAINT PROYECTO_INICIO_VNN NOT NULL,
FIN 		DATE
		CONSTRAINT PROYECTO_FIN_VNN NOT NULL,
PRESUPUESTO 	NUMBER(6,2)
);

CREATE TABLE ESTUDIANTE (
NIA NUMBER(8)
	CONSTRAINT ESTUDIANTE_NIA_PK PRIMARY KEY,
NOMBRE VARCHAR2(50)
	CONSTRAINT ESTUDIANTE_NOMBRE_VNN NOT NULL
	CHECK(NOMBRE = INITCAP(NOMBRE)),
CICLO VARCHAR2(100),
FNAC DATE
);

CREATE TABLE MOVILIDAD (
CODPROY VARCHAR2(5),
NIA NUMBER(8),
DESTINO VARCHAR2(25),
INICIO DATE,
DIA NUMBER(2)
	DEFAULT 30
	CHECK (DIA >= 30 AND DIA <=90),
BECA NUMBER(4,2)
	CHECK (BECA <= 1000),
CONSTRAINT MOVILIDAD_PK PRIMARY KEY (CODPROY,NIA),
CONSTRAINT MOVILIDAD_UK UNIQUE (NIA,INICIO),
CONSTRAINT MOVILIDAD_CODPROY_FK FOREIGN KEY (CODPROY) REFERENCES PROYECTO (CODPROY),
CONSTRAINT MOVILIDAD_NIA_FK FOREIGN KEY (NIA) REFERENCES ESTUDIANTE (NIA)
);


CREATE TABLE DOCENTE (
CODDOC VARCHAR2(4)
	CONSTRAINT DOCENTE_CODDOC_PK PRIMARY KEY,
NOMBRE VARCHAR2(50)
	CONSTRAINT DOCENTE_NOMBRE_VNN NOT NULL,
DEPARTAMENTO VARCHAR2(4)
CHECK (DEPARTAMENTO IN ('TIC' , 'HOST' , 'ING', 'AUTO'))
);

CREATE TABLE SEGUIMIENTO (
CODPROY VARCHAR2(5),
NIA NUMBER(8),
FECHA DATE
	DEFAULT SYSDATE,
OBSERVACIONES VARCHAR2(100),
COORD VARCHAR2(4)
	CHECK(COORD = INITCAP(COORD)),
CONSTRAINT SEGUIMIENTO_PK PRIMARY KEY (CODPROY,NIA,FECHA),
CONSTRAINT SEGUIMIENTO_FK FOREIGN KEY (CODPROY,NIA) REFERENCES MOVILIDAD (CODPROY,NIA) ON DELETE CASCADE,
CONSTRAINT SEGUIMIENTO_COORD_FK FOREIGN KEY (COORD) REFERENCES DOCENTE (CODDOC) ON DELETE SET NULL
);