DROP TABLE PROYECTO CASCADE CONSTRAINTS;
DROP TABLE MOVILIDAD CASCADE CONSTRAINTS;
DROP TABLE ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE SEGUIMIENTO CASCADE CONSTRAINTS;
DROP TABLE DOCENTE CASCADE CONSTRAINTS;