CREATE TABLE EQUIPO(
NOMEQ 		VARCHAR2(25),
		CONSTRAINT NOMEQ_PK PRIMARY KEY,
DIRECTOR 	VARCHAR2(100)
);

CREATE TABLE CICLISTA(
DORSAL		NUMBER(3)
		CONSTRAINT DORSAL_PK PRIMARY KEY,
NOMBRE		VARCHAR(30)
		CONSTRAINT NOMEQ_VNN NOT NULL,
EDAD		NUMBER(2),
NOMEQ		VARCHAR(25)
		CONSTRAINT NOMEQ_VNN NOT NULL,
		CONSTRAINT NOMBRE_FK REFERENCES EQUIPO (NOMEQ)
);

CREATE TABLE ETAPA(
NETAPA 		VARCHAR2(35)
		CONSTRAINT NETAPA_PK PRIMARY KEY,
KM		NUMBER(3),
SALIDA 		VARCHAR2(35),
LLEGADA 	VARCHAR2(35),
DORSAL 		NUMBER(3)
		CONSTRAINT DORSAL_FK REFERENCES CICLISTA (DORSAL),
);

CREATE TABLE PUERTO(
NOMPUERTO	VARCHAR2(35)
		CONSTRAINT NOMPUERTO_PK PRIMARY KEY,
ALTURA		NUMBER(4),
CATEGORIA	CHAR(1),
PENDIENTE	NUMBER(3,2),
NETAPA		NUMBER(2)
		CONSTRAINT NETAPA_FK REFERENCES ETAPA(NETAPA) ON DELETE CASCADE,
		CONSTRAINT NETAPA_VNN NOT NULL,
DORSAL		NUMBER(3)
		CONSTRAINT DORSAL_FK REFERENCES CICLISTA(DORSAL),
);

CREATE TABLE MAILLOT(
CODIGO		CHAR(3)
		CONSTRAINT CODIGO_PK PRIMARY KEY,
TIPO		VARCHAR2(30),
PREMIO		NUMBER(7),
COLOR		VARCHAR2(20)
);

CREATE TABLE LLEVAR(
NETAPA 		NUMBER(2)
		CONSTRAINT NETAPA_PK PRIMARY KEY,
		CONSTRAINT LLEVAR_ETAPA_FK REFERENCES ETAPA (NETAPA),
CODIGO		CHAR(3)
		CONSTRAINT CODIGO_PK PRIMARY KEY,
		CONSTRAINT LLEVAR_MAILLOT_FK REFERENCES MAILLOT (CODIGO),
DORSAL 		NUMBER(3) 
		CONSTRAINT DORSAL_VNN NOT NULL, 
		CONSTRAINT LLEVAR_CICLISTA_FK REFERENCES CICLISTA (DORSAL),
);
