CREATE USER 	lunes
IDENTIFIED BY	lunes;

GRANT SELECT ON ARTICULO TO lunes;

SELECT *
FROM ALUMNO.ARTICULO;

GRANT CREATE TABLE,UNLIMITED TABLESPACE TO lunes;


CREATE TABLE tabla1 (
C1 VARCHAR2 (10) PRIMARY KEY,
C2 NUMBER(3) NOT NULL)
TABLESPACE USERS;

DROP TABLE tabla1;