--CUIDADO QUE LOS NULOS JUEGAN MALAS PASADAS
--OBSERVAD EL RESULTADO
SELECT  CODART, 
        STOCK, 
        STOCK_MIN, 
        DECODE (SIGN (STOCK- STOCK_MIN), 1, 'STOCK SUFICIENTE', -1, 'STOCK INSUFICIENTE', 'STOCK AJUSTADO') "LEYENDA_STOCK"
FROM    ARTICULO
WHERE   PRECIO<0.5;

--SI CONSIDERAMOS QUE DESCONOCER EL STOCK ES COMO TENER 0 UNIDADES (DEPENDE DE LA REALIDAD)
SELECT  CODART, 
        NVL(STOCK,0), 
        NVL(STOCK_MIN, 0), 
        DECODE (SIGN (NVL(STOCK,0)- NVL(STOCK_MIN,0)), 1, 'STOCK SUFICIENTE', -1, 'STOCK INSUFICIENTE', 'STOCK AJUSTADO')
FROM    ARTICULO
WHERE   PRECIO<0.5;