--UTILIZANDO LIKE (NO PODEMOS)
SELECT  NOMBRE
FROM    PROVINCIA
WHERE   UPPER (NOMBRE) LIKE '___E%A';

--SIN UTILIZAR LIKE
SELECT  NOMBRE
FROM    PROVINCIA
WHERE   UPPER(SUBSTR(NOMBRE, 4, 1)) = 'E' AND  
        UPPER(SUBSTR(NOMBRE, LENGTH(NOMBRE), 1)) = 'A';

SELECT  NOMBRE
FROM    PROVINCIA
WHERE   UPPER(SUBSTR(NOMBRE, 4, 1)) = 'E' AND  
        UPPER(SUBSTR(NOMBRE, -1, 1)) = 'A';

SELECT  NOMBRE
FROM    PROVINCIA
WHERE   UPPER(SUBSTR(NOMBRE, 4, 1)) = 'E' AND  
        UPPER(SUBSTR(NOMBRE, -1)) = 'A';