--DEL AÑO 2002
 -- utilizando MOD      
SELECT  CODFAC, FECHA, CODCLI
FROM    FACTURA
WHERE   MOD(CODCLI,10)=0 AND
        TO_CHAR(FECHA, 'YYYY')= '2002';
        
-- Sin utilizar MOD 
SELECT  CODFAC, FECHA, CODCLI
FROM    FACTURA
WHERE   SUBSTR(TO_CHAR(CODCLI), -1)='0' AND
        TO_CHAR(FECHA, 'YYYY')= '2002';
        
SELECT  CODFAC, FECHA, CODCLI
FROM    FACTURA
WHERE   TO_CHAR(CODCLI) LIKE '%0' AND
        TO_CHAR(FECHA, 'YYYY')= '2002';        
        
--DEL AÑO PASADO
SELECT  CODFAC, TO_CHAR (CODCLI), FECHA
FROM    FACTURA
WHERE   SUBSTR(TO_CHAR(CODCLI), -1)='0' AND
        TO_NUMBER(TO_CHAR(FECHA, 'YYYY'))= TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-1;        

        
        
        