--AÑOS 2000, 2001, 2002
SELECT  CODFAC, FECHA
FROM    FACTURA
WHERE   TO_CHAR(FECHA, 'MM')='05' AND
        TO_NUMBER (TO_CHAR(FECHA, 'YYYY')) BETWEEN 2000 AND 2002;        
        
--DE LOS ULTIMOS 3 AÑOS
SELECT  CODFAC, FECHA
FROM    FACTURA
WHERE   TO_CHAR(FECHA, 'MM')='05' AND
        TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-TO_NUMBER(TO_CHAR(FECHA, 'YYYY')) BETWEEN 0 AND 2;        

        
        
        