-- DEL AÑO 2002
SELECT  DISTINCT CODCLI
FROM    FACTURA
WHERE   TO_CHAR(FECHA,'YYYY')= '2002' AND
        TO_CHAR(FECHA,'q')= '4';
        
-- ANTERIORES AL 4º TRIMESTRE
SELECT  DISTINCT CODCLI
FROM    FACTURA
WHERE   TO_CHAR(FECHA,'YYYY')= '2002' AND
        TO_NUMBER(TO_CHAR(FECHA,'q'))<= 4;
        