--SCRIPT SQL
--CARGA DATOS EN TABLA MITABLA:

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

INSERT INTO MITABLA VALUES (1,'AAAAAAAAA','01/01/2022');
INSERT INTO MITABLA VALUES (20,'FDSLK','01/02/2022');
INSERT INTO MITABLA VALUES (33,'adfsr�dl�fl�d',NULL);
INSERT INTO MITABLA VALUES (80,NULL,NULL);
COMMIT;