SELECT  DISTINCT NOMBRE, ETAPA.NETAPA
FROM    ETAPA, CICLISTA, LLEVAR, MAILLOT
WHERE   ETAPA.DORSAL=CICLISTA.DORSAL AND
        LLEVAR.NETAPA=ETAPA.NETAPA AND
        LLEVAR.DORSAL=CICLISTA.DORSAL AND
        LLEVAR.CODIGO=MAILLOT.CODIGO AND
        MAILLOT.COLOR='Amarillo';
        
        
