--CONSULTA CORRECTA
--SE DEBE OBSERVAR QUE SE INCLUYE ETAPA TANTO EN LA PPAL COMO EN LA SUBCONSULTA
SELECT  NOMBRE
FROM    CICLISTA, ETAPA 
WHERE   CICLISTA.DORSAL=ETAPA.DORSAL AND
        EDAD= (SELECT MIN (EDAD)
              FROM    CICLISTA, ETAPA
              WHERE   ETAPA.DORSAL=CICLISTA.DORSAL);
                 
                          
-- CUIDADO CON ESTAS CONSULTAS QUE NO SON CORRECTAS

-- COGE LA EDAD MÍNIMA DE TODOS LOS CICLISTAS (NO LOS QUE HAN GANADO ETAPAS)
SELECT  NOMBRE
FROM    CICLISTA, ETAPA
WHERE   CICLISTA.DORSAL=ETAPA.DORSAL AND
        EDAD= (SELECT MIN (EDAD)
              FROM    CICLISTA); 

-- SALEN LOS CICLISTAS QUE NO HAN GANADO ETAPAS
SELECT  NOMBRE
FROM    CICLISTA  
WHERE   EDAD= (SELECT MIN (EDAD)
              FROM    CICLISTA, ETAPA
              WHERE   ETAPA.DORSAL=CICLISTA.DORSAL);         
              