SELECT  NETAPA
FROM    ETAPA
WHERE   (SELECT COUNT (*)
        FROM    PUERTO
        WHERE   ETAPA.NETAPA=PUERTO.NETAPA)>=2;
        
--TEMA 8
SELECT  NETAPA
FROM    PUERTO
GROUP BY NETAPA
HAVING  COUNT(*)>=2;