SELECT  NETAPA, SALIDA, LLEGADA
FROM    ETAPA
WHERE   KM>190 AND
        (SELECT COUNT (*)
        FROM    PUERTO
        WHERE   ETAPA.NETAPA=PUERTO.NETAPA)>=2;
        
--TEMA 8
SELECT  PUERTO.NETAPA, SALIDA, LLEGADA
FROM    ETAPA, PUERTO
WHERE   ETAPA.NETAPA=PUERTO.NETAPA AND
        KM>190 
GROUP BY PUERTO.NETAPA, SALIDA, LLEGADA
HAVING  COUNT(*)>=2;