REM   Script: Script pruebas
REM   Primer script de pruebas para Live SQL

CREATE TABLE DEPART (
DEPT_NO     NUMBER(2) 
            CONSTRAINT DEPART_PK PRIMARY KEY,
DNOMBRE     VARCHAR2(14), 
LOC         VARCHAR2(14)
) ;

CREATE TABLE EMPLE (
EMP_NO      NUMBER(4) 
            CONSTRAINT EMPLE_PK PRIMARY KEY,
APELLIDO    VARCHAR2(10),
OFICIO      VARCHAR2(10),
DIR         NUMBER(4)
            CONSTRAINT EMPLE_EMPLE_FK REFERENCES EMPLE (EMP_NO),
FECHA_ALT   DATE,
SALARIO     NUMBER(7,2),
COMISION    NUMBER(7,2),
DEPT_NO     NUMBER(2) 
            CONSTRAINT EMPLE_DEPT_VNN NOT NULL
            CONSTRAINT EMPLE_DEPART_FK REFERENCES DEPART (DEPT_NO)
) ;

