CREATE USER PRUEBAS IDENTIFIED BY PRUEBAS
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE TO PRUEBAS;

CREATE TABLE ESTUDIANTE (
NIA NUMBER(8)
CONSTRAINT ESTUDIANTE_PK PRIMARY KEY,
NOMBRE VARCHAR2(50)
CONSTRAINT ESTUDIANTE_VNN NOT NULL);