--TRUNCADO/REDONDEO A AÑOS 'YYYY'
--LOS MESES SON IMPORTANTES 

SELECT  TRUNC (TO_DATE('10/03/19'), 'YYYY'), ROUND(TO_DATE('10/03/19'), 'YYYY')
FROM    DUAL;

SELECT  TRUNC (TO_DATE('10/07/19'), 'YYYY'), ROUND(TO_DATE('10/07/19'), 'YYYY')
FROM    DUAL;

SELECT  TRUNC (SYSDATE, 'YYYY'), ROUND(SYSDATE, 'YYYY')
FROM    DUAL;