--TRUNCADO/REDONDEO A MESES 'MM'
--LOS DÍAS SON IMPORTANTES 

SELECT  TRUNC (TO_DATE('10/03/19'), 'MM'), ROUND(TO_DATE('10/03/19'), 'MM')
FROM    DUAL;

SELECT  TRUNC (TO_DATE('16/03/19'), 'MM'), ROUND(TO_DATE('16/03/19'), 'MM')
FROM    DUAL;

SELECT  TRUNC (SYSDATE, 'MM'), ROUND(SYSDATE, 'MM')
FROM    DUAL;