CREATE TABLE PIEZA (
COD_PIEZA   VARCHAR2(3) 
            CONSTRAINT PIEZA_PK PRIMARY KEY,
NOMBRE      VARCHAR2(100) 
            CONSTRAINT PIEZA_NOMBRE_VNN NOT NULL,
COLOR       VARCHAR2(10) 
            CONSTRAINT PIEZA_COLOR_CHK CHECK (UPPER(COLOR) IN ('ROJO', 'AZUL', 'AMARILLO')),
PESO        NUMBER(5, 2) 
            CONSTRAINT PIEZA_PESO_CHK CHECK (PESO>=0 AND PESO<=100)
);

CREATE TABLE VENDEDOR (
COD_VEN     VARCHAR2(2) 
            CONSTRAINT VENDEDOR_PK PRIMARY KEY,
NOMBRE      VARCHAR2(100) 
            CONSTRAINT VENDEDOR_NOMBRE_VNN NOT NULL 
            CONSTRAINT VENDEDOR_NOMBRE_UNI UNIQUE,
SALARIO     NUMBER(6, 2) 
            DEFAULT 600 
            CONSTRAINT VENDEDOR_SALARIO_CHK CHECK (SALARIO BETWEEN 0 AND 3000),
JEFE        VARCHAR2(2) 
            CONSTRAINT VENDEDOR_VENDEDOR_FK REFERENCES VENDEDOR (COD_VEN)
);

CREATE TABLE ASIGNACION(
COD_PIEZA   VARCHAR2(3) 
            CONSTRAINT ASIGNACION_PIEZA_FK REFERENCES PIEZA ON DELETE CASCADE,
COD_VEN     VARCHAR2(2) 
            CONSTRAINT ASIGNACION_VENDEDOR_FK REFERENCES VENDEDOR ON DELETE CASCADE,
FECHA_INICIO  DATE 
              DEFAULT SYSDATE,
FECHA_FIN   DATE,
CONSTRAINT ASIGNACION_PK PRIMARY KEY (COD_PIEZA, COD_VEN, FECHA_INICIO),
CONSTRAINT ASIGNACION_FECHAS_CHK CHECK (FECHA_INICIO<FECHA_FIN)
);